import {StyleSheet} from 'react-native';
import {scale, vScale, fontScale} from '../../Helpers/Scale';

export const styles = StyleSheet.create({
  mainSearch: {
    backgroundColor: '#fff',
    flex: 1,
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#0000009c',
  },
  modalView: {
    width: '70%',
    margin: 20,
    position: 'relative',
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 35,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  MoviesHeader: {
    fontSize: fontScale(16),
    fontWeight: 'bold',
    padding: 10,
  },
  mymoview: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  closemodal: {
    backgroundColor: '#00b4e4',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 10,
    borderRadius: 10,
    position: 'absolute',
    right: 1,
  },
  addnew: {
    backgroundColor: '#00b4e4',
    alignItems: 'center',
    justifyContent: 'center',
    margin: 10,
    padding: 10,
    borderRadius: 10,
  },
  movieImg: {
    width: '100%',
    height: vScale(150),
    resizeMode: 'contain',
  },
  moviewTitle: {
    fontSize: fontScale(16),
    fontWeight: 'bold',
    color: '#00b4e4',
  },
  movieDate: {
    fontSize: fontScale(14),
    fontWeight: '500',
    color: '#ccc',
  },
  movieOverview: {
    fontSize: fontScale(14),
    fontWeight: '500',
  },
  input: {
    height: vScale(40),
    width: '100%',
    margin: 12,
    borderWidth: 1,
    borderRadius: 10,
    borderColor: '#ccc',
    padding: 10,
  },
  closeicon: {
    width: scale(10),
    height: vScale(10),
  },
  placeholdermodal: {
    width: scale(100),
    height: vScale(100),
  },
  mymoviewlist: {
    backgroundColor: 'white',
    borderRadius: 8,
    shadowColor: '#171717',
    shadowOffset: {width: -2, height: 4},
    shadowOpacity: 0.2,
    shadowRadius: 3,
    margin: 10,
    padding: 10,
    height: vScale(250),
    width: scale(200),
  },
  allMoviesList: {
    flexDirection: 'column',
    justifyContent: 'space-around',
    backgroundColor: 'white',
    borderRadius: 8,
    shadowColor: '#171717',
    shadowOffset: {width: -2, height: 4},
    shadowOpacity: 0.2,
    shadowRadius: 3,
    margin: 5,
    padding: 10,
    height: vScale(300),
    width: scale(175),
  },
});
